eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    hikari:
      maximum-pool-size: 2

  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
jwt:
  config:
    key: saas-ihrm
    ttl: 36000000
my:
  appId: 20644799
  apiKey: 6T0AbkW3xDTa0zn8VZazjtId
  secretKey: Zo4K2hm1Q2iDwTlyyxQuxQlHU4VYVlSO
  imageType: BASE64
  groupId: itcast
  url: http://localhost:8080/#/facelogin
